version: '3'

networks:
  user-net:

services:
  mongo:
    image: mongo:4.4.4
    environment:
      - MONGO_INITDB_DATABASE=nestjs_mongo
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - '27017:27017'
    networks:
      - user-net
    volumes:
      - ./mongo_data:/data/db

  # image: helloalf/microservice-user
  user:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_PORT=27017
      - MONGO_HOST=mongo
      - RABBITMQ_URI=amqp://3.131.89.227:5672
      - JWT_SECRET=KV7A8XrgCjkdBhhBUn8KbGUZRaWqaKAzKQH4FkzjVBabRYfEzWPC
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
      - user-net
